SCR_PlaceableEntitiesRegistry {
 m_sAddon "MikesInvadeandAnnexExp"
 m_sSourceDirectory "{1A6D47B0E6C35924}PrefabsEditable/IA"
 m_bExposed 1
 m_Prefabs {
  "{1A6D47B0E6C35924}PrefabsEditable/IA/E_IA_Town.et"
  "{1A6D47B0E6C35914}PrefabsEditable/IA/E_IA_City.et"
  "{1A6D47B0E6C35934}PrefabsEditable/IA/E_IA_Property.et"
  "{1A6D47B0E6C35944}PrefabsEditable/IA/E_IA_Military.et"
  "{1A6D47B0E6C35954}PrefabsEditable/IA/E_IA_SmallMilitary.et"
  "{1A6D47B0E6C35964}PrefabsEditable/IA/E_IA_Docks.et"
  "{1A6D47B0E6C35974}PrefabsEditable/IA/E_IA_RadioTower.et"
  "{1A6D47B0E6C35984}PrefabsEditable/IA/E_IA_MortarPit.et"
  "{1A6D47B0E6C35994}PrefabsEditable/IA/E_IA_Defend.et"
  "{1A6D47B0E6C35A03}PrefabsEditable/IA/E_IA_SideObjective.et"
  "{1A6D47B0E6C35A13}PrefabsEditable/IA/E_IA_HVT.et"
  "{1A6D47B0E6C35A23}PrefabsEditable/IA/E_IA_AISpawnPoint.et"
  "{1A6D47B0E6C35C11}PrefabsEditable/IA/E_IA_GmHoldPost.et"
 }
}
