IA_Config {
 m_bDynamicBaseEnabled 1
 m_iDynamicBaseChancePct 100
 m_bDynamicBaseInGm 0
 m_iDynamicBaseSizeMode 0
 m_iDynamicBaseCaptureSec 90
 m_iDynamicBaseRegroupMinSec 90
 m_iDynamicBaseRegroupMaxSec 240
 m_fDynamicBaseRegroupFraction 0.6
 m_fDynamicBaseGarrisonMultiplier 1
}
