// Generated by tools/author_base_designs.py. Mesh bounds from native Preview.
class IA_BaseCompositionCatalog
{
	static IA_BaseCompositionAsset Get(string key)
	{
		ref IA_BaseCompositionAsset asset;
		IA_BaseGunSocket socket;
		switch (key)
		{
			case "Headquarters":
				asset = IA_BaseCompositionAsset.Create(key, "{9F26A65608BE5088}Prefabs/BaseCompositions/IA_Headquarters_S_USSR_01_74129A.et", "-8.72341 -2.64587 -7.54075", "6.846 6.11494 8.62018", 74);
				break;
			case "LivingSmall":
				asset = IA_BaseCompositionAsset.Create(key, "{DF3415B16B1F5607}Prefabs/BaseCompositions/IA_LivingArea_S_USSR_01_45BA64.et", "-7.11552 -2.64587 -6.28159", "9.61424 4.59062 7.61621", 78);
				break;
			case "LivingLarge":
				asset = IA_BaseCompositionAsset.Create(key, "{16407BA1F9AF5182}Prefabs/BaseCompositions/IA_LivingArea_L_USSR_01_F66A47.et", "-18.3173 -2.64487 -21.6576", "24.3012 4.59162 21.1013", 544);
				break;
			case "Hospital":
				asset = IA_BaseCompositionAsset.Create(key, "{1ECDF45BB482580B}Prefabs/BaseCompositions/IA_FieldHospital_M_USSR_01_BCA14D.et", "-15.8272 -2.64587 -13.6751", "14.8099 4.59062 12.0355", 215);
				break;
			case "Medical":
				asset = IA_BaseCompositionAsset.Create(key, "{D3EA457771595E7B}Prefabs/BaseCompositions/IA_Tent_Medical_USSR_01_58D343.et", "-7.08141 -2.64587 -6.41875", "7.07224 4.59062 7.32121", 34);
				break;
			case "MaintenanceSmall":
				asset = IA_BaseCompositionAsset.Create(key, "{F0CBB1DE31B15682}Prefabs/BaseCompositions/IA_VehicleMaintenance_S_USSR_01_00D05F.et", "-4.15936 -1.02384 -6.419", "3.98642 2.63156 4.72535", 24);
				break;
			case "MaintenanceLarge":
				asset = IA_BaseCompositionAsset.Create(key, "{63A6B86A997F5EE5}Prefabs/BaseCompositions/IA_VehicleMaintenance_M_USSR_01_87AC7A.et", "-14.0262 -1.04035 -13.91", "11.6753 3.85156 12.1698", 149);
				break;
			case "Supply":
				asset = IA_BaseCompositionAsset.Create(key, "{D42EF810E81F5AB3}Prefabs/BaseCompositions/IA_SupplyStorage_S_USSR_01_67A6AF.et", "-7.35104 -0.998488 -7.19563", "6.95747 3.00948 4.73805", 113);
				break;
			case "Ammo":
				asset = IA_BaseCompositionAsset.Create(key, "{1B1871A8701256D2}Prefabs/BaseCompositions/IA_AmmoStorage_S_USSR_01_969D27.et", "-9.03258 -2.31643 -9.6559", "8.5221 1.82233 7.53406", 42);
				break;
			case "Fuel":
				asset = IA_BaseCompositionAsset.Create(key, "{0EB772A28DC757AD}Prefabs/BaseCompositions/IA_FuelStorage_S_USSR_01_F1FAA1.et", "-5.99355 -1.02384 -5.21021", "6.22671 2.1 1.49567", 17);
				break;
			case "Tower":
				asset = IA_BaseCompositionAsset.Create(key, "{E68CD92E6B3F5BB7}Prefabs/BaseCompositions/IA_GuardTower_S_USSR_01_BE89D1.et", "-4.06316 -1.39235 -1.84105", "4.22677 5.18308 7.2845", 27);
				break;
			case "Bunker":
				asset = IA_BaseCompositionAsset.Create(key, "{8E177CEEC1405D64}Prefabs/BaseCompositions/IA_Bunker_S_USSR_01_8981CB.et", "-6.61168 -1.4176 -4.97948", "7.45927 2.88914 7.03916", 61);
				break;
			case "PKMNest":
				asset = IA_BaseCompositionAsset.Create(key, "{B5BC555A3CCD5D91}Prefabs/BaseCompositions/IA_MachineGunNest_S_USSR_01_62738B.et", "-6.52732 -1.10356 -1.23948", "5.68394 1.42946 4.12169", 28);
				socket = asset.AddSocket(0);
				socket.Append("0 0 2", "0 0 0");
				socket.Append("0.004 0.656 -0.754", "0 0 0");
				break;
			case "NSVNest":
				asset = IA_BaseCompositionAsset.Create(key, "{973D959E8D1355BC}Prefabs/BaseCompositions/IA_MachineGunNest_S_USSR_02_25717C.et", "-6.59346 -1.54648 -5.81322", "8.41587 3.34395 4.12169", 38);
				socket = asset.AddSocket(1);
				socket.Append("0 0 2", "0 0 0");
				socket.Append("0.016 0.656 -0.677", "0 0 0");
				break;
			case "ScopedNest":
				asset = IA_BaseCompositionAsset.Create(key, "{C77FCAADCA805516}Prefabs/BaseCompositions/IA_MachineGunNest_Scoped_S_USSR_01_BC7EF0.et", "-6.59346 -1.54648 -5.81322", "8.41587 3.34395 4.12169", 38);
				socket = asset.AddSocket(2);
				socket.Append("0 0 2", "0 0 0");
				socket.Append("0.016 0.656 -0.677", "0 0 0");
				break;
			case "PKM":
				asset = IA_BaseCompositionAsset.Create(key, "{F13C6D41C1685FA5}Prefabs/BaseCompositions/IA_Sandbag_MG_USSR_01_PKM_FD76E0.et", "-3.25523 -1.10356 -2.40481", "3.72214 1.42946 2.12169", 14);
				socket = asset.AddSocket(0);
				socket.Append("0.004 0.656 -0.754", "0 0 0");
				break;
			case "NSV":
				asset = IA_BaseCompositionAsset.Create(key, "{BE5F59ACE497533B}Prefabs/BaseCompositions/IA_Sandbag_MG_USSR_01_NSV_951220.et", "-3.25523 -1.10356 -2.40481", "3.72214 1.42946 2.12169", 14);
				socket = asset.AddSocket(1);
				socket.Append("0.016 0.656 -0.677", "0 0 0");
				break;
			case "AA":
				asset = IA_BaseCompositionAsset.Create(key, "{D42DCBAB697A5CA2}Prefabs/BaseCompositions/IA_Emplacement_AA_MG_USSR_NSV_SPP_67B951.et", "-6.185 -1.3803 -6.55574", "7.49962 4.2515 6.02151", 11);
				socket = asset.AddSocket(3);
				socket.Append("0.626 0.946 1.264", "18.622 8.065 2.257");
				break;
			case "Position1":
				asset = IA_BaseCompositionAsset.Create(key, "{B1B49A98EA0A5572}Prefabs/BaseCompositions/IA_SandbagPosition_S_USSR_01_8046BE.et", "-5.67821 -1.02725 -0.743405", "6.48959 1.42946 3.52686", 21);
				break;
			case "Position2":
				asset = IA_BaseCompositionAsset.Create(key, "{C4668B3A410D51DB}Prefabs/BaseCompositions/IA_SandbagPosition_S_USSR_02_2FF0A8.et", "-5.25069 -1.04035 -1.79397", "6.00623 3.35378 4.28016", 32);
				break;
			case "Position3":
				asset = IA_BaseCompositionAsset.Create(key, "{96E75FED6734544A}Prefabs/BaseCompositions/IA_SandbagPosition_S_USSR_03_33144D.et", "-4.91848 -1.04035 -2.91382", "5.84734 2.888 4.10117", 27);
				break;
			case "Position4":
				asset = IA_BaseCompositionAsset.Create(key, "{B4CD0903EE755E2F}Prefabs/BaseCompositions/IA_SandbagPosition_S_USSR_04_5B6E67.et", "-5.57444 -1.04035 -4.89744", "6.0559 1.44032 4.38677", 37);
				break;
			case "CheckpointS":
				asset = IA_BaseCompositionAsset.Create(key, "{6942FC8914085E7E}Prefabs/BaseCompositions/IA_Checkpoint_S_USSR_01_94B65A.et", "-3.10814 -0.274128 -3.17378", "2.84757 1.46664 3.19095", 8);
				break;
			case "CheckpointM":
				asset = IA_BaseCompositionAsset.Create(key, "{55D5F6702807516A}Prefabs/BaseCompositions/IA_Checkpoint_M_USSR_01_7F0F9A.et", "-6.46404 -1.10356 -5.93959", "5.74558 2.557 5.92569", 40);
				socket = asset.AddSocket(0);
				socket.Append("-2.666 0 3.804", "0 0 0");
				socket.Append("0.004 0.656 -0.754", "0 0 0");
				break;
			case "CheckpointL":
				asset = IA_BaseCompositionAsset.Create(key, "{EB1B0129075C5272}Prefabs/BaseCompositions/IA_Checkpoint_L_USSR_01_0278AA.et", "-7.97302 -1.54648 -8.54264", "8.6234 3.34395 7.51869", 63);
				socket = asset.AddSocket(1);
				socket.Append("-3.817 0 5.397", "0 0 0");
				socket.Append("0.016 0.656 -0.677", "0 0 0");
				break;
			case "BarricadeS":
				asset = IA_BaseCompositionAsset.Create(key, "{2A955684F6465615}Prefabs/BaseCompositions/IA_Barricade_S_USSR_01_9F62D2.et", "-3.1178 -0.700619 -1.6456", "3.15496 1.46664 1.93072", 8);
				break;
			case "BarricadeM":
				asset = IA_BaseCompositionAsset.Create(key, "{20C4F648E6DB55A0}Prefabs/BaseCompositions/IA_Barricade_M_USSR_01_E8D4B0.et", "-5.27908 -0.700619 -1.75777", "5.02448 1.50087 1.71629", 15);
				break;
			case "BarricadeL":
				asset = IA_BaseCompositionAsset.Create(key, "{79F99BEC3EF8508B}Prefabs/BaseCompositions/IA_Barricade_L_USSR_01_8B3DE7.et", "-7.36494 -0.700619 -2.21857", "7.08205 1.46664 2.5349", 27);
				break;
		}
		return asset;
	}
}
