// Generated by tools/author_base_emplacements.py; do not hand-edit.
// These are candidates, not a claim of a clear firing aperture.
class IA_BaseEmplacementManifest
{
	static void Populate(IA_DynamicSiteLayout layout)
	{
		if (layout.m_iLayoutId == 0)
		{
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_01", "wall_eastN_01", "87.6 0 0.696", 90, 1, true));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastS_18", "wall_eastS_18", "87.6 0 -13.8", 90, 1, true));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontE_00", "wall_frontE_00", "7.8 0 -67.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontW_27", "wall_frontW_27", "-7.8 0 -67.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_01", "wall_westN_01", "-87.6 0 0.696", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westS_18", "wall_westS_18", "-87.6 0 -13.8", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_29", "wall_rear_29", "-1.48 0 67.6", 0, 0, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_35", "wall_rear_35", "16.276 0 67.6", 0, 0, false));
		}

		if (layout.m_iLayoutId == 1)
		{
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_00", "wall_eastN_00", "57.6 0 0.8", 90, 1, true));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_05", "wall_eastN_05", "57.6 0 15.331", 90, 1, true));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontE_00", "wall_frontE_00", "7.8 0 -47.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontW_17", "wall_frontW_17", "-7.8 0 -47.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_00", "wall_westN_00", "-57.6 0 0.8", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_05", "wall_westN_05", "-57.6 0 15.331", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_19", "wall_rear_19", "-1.469 0 47.6", 0, 0, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_25", "wall_rear_25", "16.162 0 47.6", 0, 0, false));
		}

		if (layout.m_iLayoutId == 2)
		{
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_00", "wall_eastN_00", "41.6 0 3.8", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastS_09", "wall_eastS_09", "41.6 0 -10.55", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontE_00", "wall_frontE_00", "5.8 0 -35.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontE_11", "wall_frontE_11", "38.342 0 -35.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_00", "wall_westN_00", "-41.6 0 3.8", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_05", "wall_westN_05", "-41.6 0 18.118", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_19", "wall_rear_19", "14.75 0 35.6", 0, 0, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_07", "wall_rear_07", "-20.65 0 35.6", 0, 0, false));
		}

		if (layout.m_iLayoutId == 3)
		{
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_09", "wall_eastN_09", "27.6 0 22.006", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_15", "wall_eastN_15", "27.6 0 39.476", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontE_03", "wall_frontE_03", "13.863 0 -45.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontW_05", "wall_frontW_05", "-13.863 0 -45.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_00", "wall_westN_00", "-27.6 0 -4.2", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_09", "wall_westN_09", "-27.6 0 22.006", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_15", "wall_rear_15", "15.805 0 45.6", 0, 0, false));
		}

		if (layout.m_iLayoutId == 4)
		{
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_00", "wall_eastN_00", "29.6 0 7.8", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_05", "wall_eastN_05", "29.6 0 22.383", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontW_05", "wall_frontW_05", "-14.613 0 -25.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontW_00", "wall_frontW_00", "-29.3 0 -25.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_00", "wall_westN_00", "-29.6 0 7.8", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_15", "wall_rear_15", "14.65 0 25.6", 0, 0, false));
		}

		if (layout.m_iLayoutId == 5)
		{
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastN_00", "wall_eastN_00", "15.6 0 -4.2", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_eastS_01", "wall_eastS_01", "15.6 0 -18.55", 90, 1, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_frontW_03", "wall_frontW_03", "-8.175 0 -21.6", 180, 2, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_00", "wall_westN_00", "-15.6 0 -4.2", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_westN_09", "wall_westN_09", "-15.6 0 21.3", 270, 3, false));
			layout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("mg_wall_rear_11", "wall_rear_11", "15.3 0 21.6", 0, 0, false));
		}

	}
}
