// Generated by tools/author_headquarters.py. Mesh bounds from native Preview.
class IA_HeadquartersCatalog
{
	static IA_BaseCompositionAsset Get(string key)
	{
		ref IA_BaseCompositionAsset asset;
		IA_BaseGunSocket socket;
		switch (key)
		{
			case "HQWallA":
				asset = IA_BaseCompositionAsset.Create(key, "{DA1FB8F1819C5BB1}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallRun_A.et", "-3.17215 -1.00197 -0.489258", "2.698 3.32718 0.478726", 5);
				break;
			case "HQWallB":
				asset = IA_BaseCompositionAsset.Create(key, "{3567DBF56FF65473}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallRun_B.et", "-3.17215 -1.00197 -0.489258", "2.698 3.32718 0.478726", 5);
				break;
			case "HQWallC":
				asset = IA_BaseCompositionAsset.Create(key, "{3F17DF179E1D5E53}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallRun_C.et", "-3.17215 -1.00197 -0.489258", "2.698 3.32783 0.478726", 5);
				break;
			case "HQWallPanel":
				asset = IA_BaseCompositionAsset.Create(key, "{1A3697B90FF35A30}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallPanel.et", "-1.82315 -1.00197 -0.489258", "1.349 3.32718 0.478726", 4);
				break;
			case "HQCasematePKM":
				asset = IA_BaseCompositionAsset.Create(key, "{FE256D53A25E5060}Prefabs/BaseCompositions/Headquarters/IA_HQ_Casemate_PKM.et", "-3.00045 -3.0444 -3.20678", "3.00481 3.21632 0.573949", 13);
				socket = asset.AddSocket(0);
				socket.Append("0.004 0.656 -0.224", "0 0 0");
				break;
			case "HQCasemateNSV":
				asset = IA_BaseCompositionAsset.Create(key, "{6456466BBC0C5745}Prefabs/BaseCompositions/Headquarters/IA_HQ_Casemate_NSV.et", "-3.00045 -3.0444 -3.20678", "3.00481 3.21632 0.815849", 14);
				socket = asset.AddSocket(1);
				socket.Append("0.016 0.656 -0.147", "0 0 0");
				break;
			case "HQCommand":
				asset = IA_BaseCompositionAsset.Create(key, "{6C2174ECD0E05F93}Prefabs/BaseCompositions/Headquarters/IA_HQ_Command_GuardHouse.et", "-9.15488 -3.76303 -8.78409", "9.19859 5.74314 5.19055", 9);
				break;
			case "HQBarracks":
				asset = IA_BaseCompositionAsset.Create(key, "{5D729180F6AA55B4}Prefabs/BaseCompositions/Headquarters/IA_HQ_Barracks.et", "-7.96795 -5.8833 -21.5845", "7.9685 5.79926 19.1445", 15);
				break;
			case "HQShelter":
				asset = IA_BaseCompositionAsset.Create(key, "{6D804238B8E85DF1}Prefabs/BaseCompositions/Headquarters/IA_HQ_Shelter.et", "-5.01992 -0.968736 -4.65319", "5.52391 5.57435 2.45377", 4);
				break;
			case "HQPillbox":
				asset = IA_BaseCompositionAsset.Create(key, "{3522264FEE8A542D}Prefabs/BaseCompositions/Headquarters/IA_HQ_Pillbox.et", "-1.47213 -0.019368 -2.89458", "1.49141 4.86042 2.70566", 5);
				break;
			case "HQTower":
				asset = IA_BaseCompositionAsset.Create(key, "{22675F12AD125CE2}Prefabs/BaseCompositions/Headquarters/IA_HQ_Tower.et", "-1.14041 -1.97537 -1.13225", "1.15152 6.78584 3.92874", 4);
				break;
			case "HQGuardBox":
				asset = IA_BaseCompositionAsset.Create(key, "{A36090ED85CF5A3A}Prefabs/BaseCompositions/Headquarters/IA_HQ_GuardBox.et", "-1.12041 -0.693703 -1.14685", "1.1268 3.38755 1.116", 3);
				break;
			case "HQTeeth":
				asset = IA_BaseCompositionAsset.Create(key, "{84852BA8BD7157AA}Prefabs/BaseCompositions/Headquarters/IA_HQ_Belt_Teeth.et", "-2.18524 0.00402 -0.845426", "2.18524 1.29187 0.785238", 6);
				break;
			case "HQHedgehogs":
				asset = IA_BaseCompositionAsset.Create(key, "{021016CFA51A5DEF}Prefabs/BaseCompositions/Headquarters/IA_HQ_Belt_Hedgehogs.et", "-2.45271 -0.008152 -1.37231", "2.58766 1.46664 1.20337", 5);
				break;
			case "HQWire":
				asset = IA_BaseCompositionAsset.Create(key, "{465135458FFE52FA}Prefabs/BaseCompositions/Headquarters/IA_HQ_Belt_Wire.et", "-1.70951 -0.693078 -1.0284", "1.73724 1.77116 1.01127", 4);
				break;
			case "HQCamoWallA":
				asset = IA_BaseCompositionAsset.Create(key, "{E47BBD43DC925CB6}Prefabs/BaseCompositions/Headquarters/IA_HQ_CamoWall_A.et", "-3.40212 -0.172884 -1.2535", "3.21249 2.18406 1.27824", 7);
				break;
			case "HQCamoWallB":
				asset = IA_BaseCompositionAsset.Create(key, "{0DD97793B78E5ADC}Prefabs/BaseCompositions/Headquarters/IA_HQ_CamoWall_B.et", "-3.40212 -0.175748 -1.2535", "2.83962 2.18406 1.27824", 6);
				break;
			case "HQCamoWallC":
				asset = IA_BaseCompositionAsset.Create(key, "{C7006CDDB3B7538F}Prefabs/BaseCompositions/Headquarters/IA_HQ_CamoWall_C.et", "-2.83145 -0.175748 -1.2535", "3.21249 2.18406 1.27824", 6);
				break;
			case "HQCamoWallPanel":
				asset = IA_BaseCompositionAsset.Create(key, "{E2D884FB74355BF1}Prefabs/BaseCompositions/Headquarters/IA_HQ_CamoWall_Panel.et", "-2.05312 -0.172884 -1.2535", "1.86349 2.18406 1.27824", 5);
				break;
			case "HQCamoWallLongA":
				asset = IA_BaseCompositionAsset.Create(key, "{DA3973E232785056}Prefabs/BaseCompositions/Headquarters/IA_HQ_CamoWall_LongA.et", "-4.75112 -0.175748 -1.2535", "4.56149 2.18406 1.27824", 8);
				break;
			case "HQCamoWallLongB":
				asset = IA_BaseCompositionAsset.Create(key, "{C2AF401CE96E5585}Prefabs/BaseCompositions/Headquarters/IA_HQ_CamoWall_LongB.et", "-4.75112 -0.172884 -1.2535", "4.56149 2.18406 1.27824", 9);
				break;
			case "HQGateNarrow":
				asset = IA_BaseCompositionAsset.Create(key, "{9BE84B07F4705DAC}Prefabs/BaseCompositions/Headquarters/IA_HQ_Gate_Narrow.et", "-7.06648 -3 -3.85917", "7.07639 9.4317 4.30784", 20);
				break;
			case "HQGateWide":
				asset = IA_BaseCompositionAsset.Create(key, "{A6FC6376A38458B5}Prefabs/BaseCompositions/Headquarters/IA_HQ_Gate_Wide.et", "-8.41548 -3 -3.85917", "8.42539 9.4317 4.30784", 20);
				break;
			case "HQSideGateNarrow":
				asset = IA_BaseCompositionAsset.Create(key, "{0DA966BB462B5D7D}Prefabs/BaseCompositions/Headquarters/IA_HQ_SideGate_Narrow.et", "-5.94912 -0.500209 -1.2535", "5.75949 2.18406 3.89538", 10);
				break;
			case "HQSideGateWide":
				asset = IA_BaseCompositionAsset.Create(key, "{2046084A8B5A5910}Prefabs/BaseCompositions/Headquarters/IA_HQ_SideGate_Wide.et", "-7.29812 -0.500209 -1.2535", "7.10849 2.18406 3.89538", 12);
				break;
			case "HQChicane":
				asset = IA_BaseCompositionAsset.Create(key, "{9B720F62DC465ED7}Prefabs/BaseCompositions/Headquarters/IA_HQ_Chicane.et", "-3.81699 -0.013245 -4.59538", "3.92731 1.44032 3.20729", 6);
				break;
			case "HQCheckpointPost":
				asset = IA_BaseCompositionAsset.Create(key, "{5FB4AADCA91A5430}Prefabs/BaseCompositions/Headquarters/IA_HQ_CheckpointPost.et", "-4.03916 -0.554139 -2.9683", "4.0019 2.78914 3.64309", 7);
				break;
			case "HQCheckpointNest":
				asset = IA_BaseCompositionAsset.Create(key, "{28CB2678FEF458A0}Prefabs/BaseCompositions/Headquarters/IA_HQ_CheckpointNest.et", "-0.86352 -0.159933 -1.88987", "1.31652 1.32946 2.99929", 6);
				break;
			case "HQSquare":
				asset = IA_BaseCompositionAsset.Create(key, "{745B7473BDF25649}Prefabs/BaseCompositions/Headquarters/IA_HQ_Square.et", "-3.93539 -0.502811 -2.093", "1.77048 5.04647 2.63927", 7);
				break;
			case "HQRoadPlates":
				asset = IA_BaseCompositionAsset.Create(key, "{4B1941EDBFF55222}Prefabs/BaseCompositions/Headquarters/IA_HQ_Road_Plates.et", "-3.87005 -0.202161 -3.85917", "3.86218 0.021881 3.86403", 11);
				break;
			case "HQRoadPlatesShort":
				asset = IA_BaseCompositionAsset.Create(key, "{E26D9D5C05855B07}Prefabs/BaseCompositions/Headquarters/IA_HQ_Road_PlatesShort.et", "-3.87005 -0.202161 -1.92917", "3.86218 0.021881 1.93403", 7);
				break;
			case "HQDuckboards":
				asset = IA_BaseCompositionAsset.Create(key, "{EA01F348BC4557D6}Prefabs/BaseCompositions/Headquarters/IA_HQ_Path_Duckboards.et", "-0.627688 -1.5e-05 -3.80394", "0.627688 0.100533 3.80394", 5);
				break;
			case "HQDuckboard":
				asset = IA_BaseCompositionAsset.Create(key, "{59AE2D0B25E252F2}Prefabs/BaseCompositions/Headquarters/IA_HQ_Path_Duckboard.et", "-0.627688 -1.5e-05 -1.90394", "0.623349 0.100533 1.88207", 4);
				break;
			case "HQPlateStack":
				asset = IA_BaseCompositionAsset.Create(key, "{D9554A76E19D5AC3}Prefabs/BaseCompositions/Headquarters/IA_HQ_PlateStack.et", "-2.09175 -0.202161 -1.12664", "2.21628 1.88876 3.52821", 5);
				break;
			case "HQDirtPatch":
				asset = IA_BaseCompositionAsset.Create(key, "{26F1DD4512DC595F}Prefabs/BaseCompositions/Headquarters/IA_HQ_Dirt_Patch.et", "-2.5 0 -2.5", "2.5 0.2 2.5", 3);
				break;
			case "HQDirtWorn":
				asset = IA_BaseCompositionAsset.Create(key, "{9E2F15674C3956B0}Prefabs/BaseCompositions/Headquarters/IA_HQ_Dirt_Worn.et", "-4 0 -4", "4 0.2 4", 5);
				break;
			case "HQDirtTrack":
				asset = IA_BaseCompositionAsset.Create(key, "{B96691E6DFC05192}Prefabs/BaseCompositions/Headquarters/IA_HQ_Dirt_Track.et", "-4 0 -4", "4 0.2 4", 5);
				break;
			case "HQDirtCross":
				asset = IA_BaseCompositionAsset.Create(key, "{5688CAA6D35B5507}Prefabs/BaseCompositions/Headquarters/IA_HQ_Dirt_Cross.et", "-3 0 -3", "3 0.2 3", 3);
				break;
			case "VigBriefing":
				asset = IA_BaseCompositionAsset.Create(key, "{986F4B80B0BE52E0}Prefabs/DynamicBase/IA_Dressing_BriefingLit.et", "-2.3 0 -2.6", "2.3 2.5 2.6", 11);
				break;
			case "VigComms":
				asset = IA_BaseCompositionAsset.Create(key, "{D7D10DFBACA05AD0}Prefabs/DynamicBase/IA_Dressing_CommsLit.et", "-2 0 -1.3", "2 2.5 1.3", 7);
				break;
			case "VigPower":
				asset = IA_BaseCompositionAsset.Create(key, "{3F22F8B9E0EB5442}Prefabs/DynamicBase/IA_Dressing_Power.et", "-2 0 -2.5", "2 2.5 2.5", 9);
				break;
			case "VigKitchen":
				asset = IA_BaseCompositionAsset.Create(key, "{7381F407AD8A54B8}Prefabs/DynamicBase/IA_Dressing_KitchenLit.et", "-3.5 0 -3.2", "3.5 2.5 3.2", 8);
				break;
			case "VigMess":
				asset = IA_BaseCompositionAsset.Create(key, "{06111FFC070A5834}Prefabs/DynamicBase/IA_Dressing_MessLit.et", "-1.7 0 -1.5", "1.7 2.5 1.5", 9);
				break;
			case "VigRest":
				asset = IA_BaseCompositionAsset.Create(key, "{754823CC537E5D85}Prefabs/DynamicBase/IA_Dressing_Rest.et", "-2 0 -1.8", "2 2.5 1.8", 6);
				break;
			case "VigWash":
				asset = IA_BaseCompositionAsset.Create(key, "{AB8A3CB589625084}Prefabs/DynamicBase/IA_Dressing_WaterWash.et", "-1.4 0 -1.2", "1.4 2.5 1.2", 7);
				break;
			case "VigWater":
				asset = IA_BaseCompositionAsset.Create(key, "{CE0933F9935A5FD4}Prefabs/DynamicBase/IA_Dressing_BulkWater.et", "-2.2 0 -3.4", "2.2 2.5 3.4", 6);
				break;
			case "VigSanitation":
				asset = IA_BaseCompositionAsset.Create(key, "{6F3672FEE4B857A1}Prefabs/DynamicBase/IA_Dressing_Sanitation.et", "-2.4 0 -2.8", "2.4 2.5 2.8", 7);
				break;
			case "VigWaste":
				asset = IA_BaseCompositionAsset.Create(key, "{A70917953C1D58AB}Prefabs/DynamicBase/IA_Dressing_Waste.et", "-1 0 -0.7", "1 2.5 0.7", 5);
				break;
			case "VigStores":
				asset = IA_BaseCompositionAsset.Create(key, "{EBACA024C71C5CAF}Prefabs/DynamicBase/IA_Dressing_Stores.et", "-1.8 0 -2.9", "1.8 2.5 2.9", 8);
				break;
			case "VigStoresCovered":
				asset = IA_BaseCompositionAsset.Create(key, "{674112EA1BA85649}Prefabs/DynamicBase/IA_Dressing_StoresCovered.et", "-1.9 0 -1.6", "1.9 2.5 1.6", 8);
				break;
			case "VigWorkshop":
				asset = IA_BaseCompositionAsset.Create(key, "{965FEDAFCD3F54D5}Prefabs/DynamicBase/IA_Dressing_WorkshopLit.et", "-2 0 -1.3", "2 2.5 1.3", 9);
				break;
			case "VigMedical":
				asset = IA_BaseCompositionAsset.Create(key, "{A9D76F51AE7B5D37}Prefabs/DynamicBase/IA_Dressing_MedicalLit.et", "-2 0 -2", "2 2.5 2", 8);
				break;
			case "VigLight":
				asset = IA_BaseCompositionAsset.Create(key, "{8726E742FEE65661}Prefabs/DynamicBase/IA_Dressing_EntranceLight.et", "-2 0 -1.5", "2 2.5 1.5", 4);
				break;
		}
		return asset;
	}
}
