// Generated by tools/author_headquarters.py. Mesh bounds from native Preview.
class IA_HeadquartersCatalog
{
	static IA_BaseCompositionAsset Get(string key)
	{
		ref IA_BaseCompositionAsset asset;
		IA_BaseGunSocket socket;
		switch (key)
		{
			case "HQWallA":
				asset = IA_BaseCompositionAsset.Create(key, "{DA1FB8F1819C5BB1}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallRun_A.et", "-3.17215 -1.00197 -0.489258", "2.698 3.32718 0.478726", 5);
				break;
			case "HQWallB":
				asset = IA_BaseCompositionAsset.Create(key, "{3567DBF56FF65473}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallRun_B.et", "-3.17215 -1.00197 -0.489258", "2.698 3.32718 0.478726", 5);
				break;
			case "HQWallC":
				asset = IA_BaseCompositionAsset.Create(key, "{3F17DF179E1D5E53}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallRun_C.et", "-3.17215 -1.00197 -0.489258", "2.698 3.32783 0.478726", 5);
				break;
			case "HQWallPanel":
				asset = IA_BaseCompositionAsset.Create(key, "{1A3697B90FF35A30}Prefabs/BaseCompositions/Headquarters/IA_HQ_WallPanel.et", "-1.82315 -1.00197 -0.489258", "1.349 3.32718 0.478726", 4);
				break;
			case "HQCasematePKM":
				asset = IA_BaseCompositionAsset.Create(key, "{FE256D53A25E5060}Prefabs/BaseCompositions/Headquarters/IA_HQ_Casemate_PKM.et", "-3.00045 -3.0444 -3.20678", "3.00481 3.21632 0.573949", 13);
				socket = asset.AddSocket(0);
				socket.Append("0.004 0.656 -0.224", "0 0 0");
				break;
			case "HQCasemateNSV":
				asset = IA_BaseCompositionAsset.Create(key, "{6456466BBC0C5745}Prefabs/BaseCompositions/Headquarters/IA_HQ_Casemate_NSV.et", "-3.00045 -3.0444 -3.20678", "3.00481 3.21632 0.815849", 14);
				socket = asset.AddSocket(1);
				socket.Append("0.016 0.656 -0.147", "0 0 0");
				break;
			case "HQCommand":
				asset = IA_BaseCompositionAsset.Create(key, "{6C2174ECD0E05F93}Prefabs/BaseCompositions/Headquarters/IA_HQ_Command_GuardHouse.et", "-9.15488 -3.76303 -8.78409", "9.19859 5.74314 5.19055", 6);
				break;
			case "HQBarracks":
				asset = IA_BaseCompositionAsset.Create(key, "{5D729180F6AA55B4}Prefabs/BaseCompositions/Headquarters/IA_HQ_Barracks.et", "-7.96795 -5.8833 -21.5845", "7.9685 5.79926 19.1445", 5);
				break;
			case "HQShelter":
				asset = IA_BaseCompositionAsset.Create(key, "{6D804238B8E85DF1}Prefabs/BaseCompositions/Headquarters/IA_HQ_Shelter.et", "-5.01992 -0.968736 -4.65319", "5.52391 5.57435 2.45377", 3);
				break;
			case "HQPillbox":
				asset = IA_BaseCompositionAsset.Create(key, "{3522264FEE8A542D}Prefabs/BaseCompositions/Headquarters/IA_HQ_Pillbox.et", "-1.47213 -0.019368 -2.89458", "1.49141 4.86042 2.70566", 3);
				break;
			case "HQTower":
				asset = IA_BaseCompositionAsset.Create(key, "{22675F12AD125CE2}Prefabs/BaseCompositions/Headquarters/IA_HQ_Tower.et", "-1.14041 -1.97537 -1.13225", "1.15152 6.78584 3.92874", 4);
				break;
			case "HQGuardBox":
				asset = IA_BaseCompositionAsset.Create(key, "{A36090ED85CF5A3A}Prefabs/BaseCompositions/Headquarters/IA_HQ_GuardBox.et", "-1.12041 -0.693703 -1.14685", "1.1268 3.38755 1.116", 3);
				break;
			case "HQTeeth":
				asset = IA_BaseCompositionAsset.Create(key, "{84852BA8BD7157AA}Prefabs/BaseCompositions/Headquarters/IA_HQ_Belt_Teeth.et", "-2.18524 0.00402 -0.845426", "2.18524 1.29187 0.785238", 6);
				break;
			case "HQHedgehogs":
				asset = IA_BaseCompositionAsset.Create(key, "{021016CFA51A5DEF}Prefabs/BaseCompositions/Headquarters/IA_HQ_Belt_Hedgehogs.et", "-2.45271 -0.008152 -1.37231", "2.58766 1.46664 1.20337", 5);
				break;
			case "HQWire":
				asset = IA_BaseCompositionAsset.Create(key, "{465135458FFE52FA}Prefabs/BaseCompositions/Headquarters/IA_HQ_Belt_Wire.et", "-1.70951 -0.693078 -1.0284", "1.73724 1.77116 1.01127", 4);
				break;
		}
		return asset;
	}
}
