ActionManager {
 Actions {
  Action IA_HeliPaintMenu {
   InputSource InputSourceSum "{9F313F5C6282C9E9}" {
    Sources {
     InputSourceValue "{3089EF9FC72A3942}" {
      FilterPreset "click"
      Input "keyboard:KC_I"
      Filter InputFilterDown "{6B0FAF35B52D93FD}" {
      }
     }
     InputSourceValue "{E9FC221736E810B9}" {
      FilterPreset "gamepad:hold"
      Input "gamepad0:pad_left"
      Filter InputFilterHoldOnce "{85F2273EFB495526}" {
       HoldDuration 750
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext IA_HeliPilotContext {
   Priority 10
   Flags 0x2 0
   ActionRefs {
    "IA_HeliPaintMenu"
   }
  }
 }
}
