MenuManager {
 MenuPresets {
  MenuPreset IA_StatisticsMenu {
   Layout "{BCA1F26D33DC8FB0}UI/IA_StatsMenu.layout"
   Class "IA_StatisticsMenu"
  }
  MenuPreset IA_AdminConfigMenu {
   Layout "{5A9D5E0BA49C579F}UI/IA_AdminMenu.layout"
   Class "IA_AdminConfigMenu"
  }
 }
}