SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{5D06D2EB51A99178}" {
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{1E59D7249F37CE5F}" {
     m_sActionName "IA_HeliPaintMenu"
     m_sDisplayName "Paint bay (pilot seat)"
     m_sPreset "click"
    }
   }
  }
 }
}
