"""Author bounded, reproducible station candidates without changing base modules.

Only horizontal envelopes are certified here. Runtime support/muzzle tests are
mandatory; these tall stock walls commonly reject the low tripod weapons.
Run with -B. --check verifies checked-in output without writing anything.
"""
from pathlib import Path
import argparse
import json
import math
import re
import sys

sys.dont_write_bytecode = True
from check_dynamic_base_layouts import read_layout, TEXT, NUMBER

ROOT = Path(__file__).resolve().parents[1]
NAMES = ['Full', 'Compact', 'Courtyard', 'Roadside', 'CommandPost', 'RallyPost']


def overlap(a, b, margin=0):
    return min(a[2], b[2]) - max(a[0], b[0]) > -margin and min(a[3], b[3]) - max(a[1], b[1]) > -margin


def envelope(x, z, yaw):
    # Whole traverse/body envelope plus inward 1.2 x 2 m access strip.
    a = math.radians(yaw)
    corners = [(x + math.cos(a)*u + math.sin(a)*v,
                z - math.sin(a)*u + math.cos(a)*v)
               for u in (-1.5, 1.5) for v in (-4.0, 1.25)]
    return (min(p[0] for p in corners), min(p[1] for p in corners),
            max(p[0] for p in corners), max(p[1] for p in corners))


def generate():
    scenes = {}
    for name in NAMES:
        w, d, radius, capture, cross, guards, boxes, posts = read_layout(name)
        section = TEXT.split(f'static IA_DynamicSiteLayout Create{name}()', 1)[1].split('return layout;', 1)[0]
        panels = []
        for panel, args in re.findall(r'AddCover\("([^"]+)", (.*)\);', section):
            x, z, yaw, style, side = map(float, re.findall(NUMBER, args))
            panels.append((panel, x, z, int(style), int(side)))
        # Include all fallback infantry spawn posts used at boosted max budget.
        budget = round(guards * 1.75)
        count = 2 + math.ceil(max(0, budget-4)/4)
        for _, x, z, _, _ in panels[:max(0, count-len(posts))]:
            length = math.hypot(x, z)
            posts.append((x-x/length*6, z-z/length*6))
        routes = [(-1.2, -d, 1.2, max(cross, capture[1])+1.2),
                  (-w, cross-1.2, w, cross+1.2)]
        selected = []
        for side in (1, 2, 3, 0):
            yaw = {0:0, 1:90, 2:180, 3:270}[side]
            candidates = [p for p in panels if p[4] == side and p[3] in (1, 2, 3)]
            candidates.sort(key=lambda p: (abs(p[1])+abs(p[2]), p[0]))
            on_side = 0
            for panel, x, z, style, _ in candidates:
                for offset in (1.5, 2.0, 2.5):
                    px = round(x-math.sin(math.radians(yaw))*offset, 4)
                    pz = round(z-math.cos(math.radians(yaw))*offset, 4)
                    box = envelope(px, pz, yaw)
                    if box[0] < -w or box[1] < -d or box[2] > w or box[3] > d:
                        continue
                    if any(overlap(box, b) for key, b in boxes if not key.startswith(('wall_', 'dressing_'))):
                        continue
                    if any(overlap(box, b) for b in routes):
                        continue
                    if any(overlap(box, (gx-1.3,gz-1.3,gx+1.3,gz+1.3)) for gx,gz in posts):
                        continue
                    if any(math.hypot(px-s['position'][0],pz-s['position'][2]) < 12 for s in selected):
                        continue
                    selected.append(dict(id=f'mg_{panel}', panel=panel, side=side, yaw=yaw,
                                         heavy=name in ('Full','Compact') and side==1,
                                         position=[px,0,pz], setback=offset))
                    on_side += 1
                    break
                if on_side == 2:
                    break
        assert len(selected) <= 8
        scenes[name] = selected
    manifest = dict(version=1, status='bounded candidates; live collision approval required',
                    stock_measurement='Workbench preview 2026-09-05; IA_BaseEmplacementProbe',
                    hardware=dict(PKM=dict(bounds=[[-.385083,-.013929,-.696341],[.385083,.428489,.797949]],
                                           preview_entities=6, loaded=99, chambered=1, reserve=300, reload_seconds=7.5,
                                           feet_status='conservative footprint samples; not contact-mesh certification'),
                                  NSV=dict(bounds=[[-.362114,-.012922,-.979337],[.444671,.692434,.962849]],
                                           preview_entities=7, loaded=49, chambered=1, reserve=150, reload_seconds=15,
                                           feet_status='stock leg IK target positions')),
                    scenes=scenes)
    lines = ['// Generated by tools/author_base_emplacements.py; do not hand-edit.',
             '// These are candidates, not a claim of a clear firing aperture.',
             'class IA_BaseEmplacementManifest', '{',
             '\tstatic void Populate(IA_DynamicSiteLayout layout)', '\t{']
    for i, name in enumerate(NAMES):
        lines += [f'\t\tif (layout.m_iLayoutId == {i})', '\t\t{']
        for s in scenes[name]:
            p = ' '.join(f'{v:g}' for v in s['position'])
            heavy = str(s['heavy']).lower()
            lines.append(f'\t\t\tlayout.m_aEmplacements.Insert(IA_DynamicBaseEmplacementSpec.Create("{s["id"]}", "{s["panel"]}", "{p}", {s["yaw"]}, {s["side"]}, {heavy}));')
        lines += ['\t\t}', '']
    lines += ['\t}', '}', '']
    svg = ['<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="650" viewBox="0 0 1080 650">',
           '<rect width="1080" height="650" fill="#101923"/>',
           '<g fill="#dce8ef" font-family="sans-serif"><text x="20" y="25" font-size="18">Dynamic-base emplacement candidates — not live-certified firing positions</text>',
           '<text x="20" y="48" font-size="12">Unchanged walls/buildings. Green: PKM. Orange: NSV with PKM fallback. Pale boxes: reserved access/sweep.</text></g>']
    for i, name in enumerate(NAMES):
        cx, cy = 180 + (i % 3)*360, 195 + (i // 3)*285
        scale = 1.4
        _, _, _, _, _, _, boxes, _ = read_layout(name)
        svg.append(f'<text x="{cx-155}" y="{cy-112}" fill="#dce8ef" font-size="16" font-family="sans-serif">{name}</text>')
        for key, (x0,z0,x1,z1) in boxes:
            color = '#7d929f' if key.startswith('wall_') else '#253d50'
            svg.append(f'<rect x="{cx+x0*scale:.2f}" y="{cy-z1*scale:.2f}" width="{(x1-x0)*scale:.2f}" height="{(z1-z0)*scale:.2f}" fill="{color}"/>')
        for index, station in enumerate(scenes[name], 1):
            x, _, z = station['position']
            a,b,c,d = envelope(x,z,station['yaw'])
            svg.append(f'<rect x="{cx+a*scale:.2f}" y="{cy-d*scale:.2f}" width="{(c-a)*scale:.2f}" height="{(d-b)*scale:.2f}" fill="#bdd9ed" fill-opacity=".3"/>')
            color = '#ffad55' if station['heavy'] else '#75df96'
            svg.append(f'<circle cx="{cx+x*scale:.2f}" cy="{cy-z*scale:.2f}" r="3" fill="{color}"><title>{station["id"]}</title></circle>')
            svg.append(f'<text x="{cx+x*scale+4:.2f}" y="{cy-z*scale-4:.2f}" fill="{color}" font-size="9" font-family="sans-serif">{index}</text>')
    svg += ['<text x="20" y="620" fill="#dce8ef" font-size="12" font-family="sans-serif">Stock muzzle heights: PKM 0.362 m; NSV 0.539 m. Most existing sandbag panels obstruct these low guns.</text>', '</svg>', '']
    return {ROOT/'docs/dynamic-base-emplacements.json': json.dumps(manifest, indent=2)+'\n',
            ROOT/'Scripts/Game/IA_BaseEmplacementManifest.c': '\n'.join(lines),
            ROOT/'docs/dynamic-base-emplacements.svg': '\n'.join(svg)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            assert path.read_text(encoding='utf-8') == content, f'stale authoring output: {path}'
        else:
            path.write_text(content, encoding='utf-8')
        print(path.relative_to(ROOT))


if __name__ == '__main__':
    main()
